package search

import (
	"fmt"
	"math/rand"
	"strings"
	"time"
)

var (
	Web   = fakeSearch("web")
	Image = fakeSearch("image")
	Video = fakeSearch("video")
	All   = []Search{Web, Image, Video}
)

// Result is a search result
type Result string

// Search is a search delegate
type Search func(query string) Result

// fakeSearch creates a fake search of the specified kind
func fakeSearch(kind string) Search {
	return func(query string) Result {
		time.Sleep(time.Duration(rand.Intn(100)) * time.Millisecond)
		return Result(fmt.Sprintf("%s result for %s", kind, query))
	}
}

// Google1 -> sequential search one by one
func Google1(query string) (results []Result) {
	for _, s := range All {
		results = append(results, s(query))
	}
	return
}

// Google2 -> run concurrently and wait for results
func Google2(query string) (results []Result) {
	c := make(chan Result)
	for _, s := range All {
		go func(c chan Result, s Search, q string) {
			c <- s(q)
		}(c, s, query)
	}

	for i := 0; i < len(All); i++ {
		results = append(results, <-c)
	}
	return
}

// Google3 exit on timeout collecting all
// results that are ready
func Google3(query string) (results []Result) {
	c := make(chan Result)
	for _, s := range All {
		go func(c chan Result, s Search, q string) {
			c <- s(q)
		}(c, s, query)
	}

	t := time.After(60 * time.Millisecond)
	for {
		select {
		case r := <-c:
			results = append(results, r)
		case <-t:
			return
		}
	}
}

// First returns the first result generated by the search engines
func First(query string, replicas ...Search) Result {
	c := make(chan Result)
	search := func(s Search) { c <- s(query) }
	for _, r := range replicas {
		go search(r)
	}
	return <-c
}

// Google4 search with timeout and replication
func Google4(query string) (results []Result) {
	Image1 := fakeSearch("image1")
	Image2 := fakeSearch("image2")
	Video1 := fakeSearch("video1")
	Video2 := fakeSearch("video2")
	Web1 := fakeSearch("web1")
	Web2 := fakeSearch("web2")

	c := make(chan Result)

	go func() { c <- First(query, Image1, Image2) }()
	go func() { c <- First(query, Video1, Video2) }()
	go func() { c <- First(query, Web1, Web2) }()

	t := time.After(50 * time.Millisecond)
	for {
		select {
		case r := <-c:
			results = append(results, r)
		case <-t:
			return
		}
	}
}

// DoSearch starts the search and prints out the results
func DoSearch(search func(query string) []Result) {
	rand.Seed(time.Now().UnixNano())

	start := time.Now()
	results := search("golang")
	elapsed := time.Since(start)

	// fmt.Printf("%#v\n", results)
	var strs []string
	for _, r := range results {
		strs = append(strs, string(r))
	}
	fmt.Println(strings.Join(strs, "\n"))
	fmt.Println(elapsed)
}

// RunSearches runs all the search cases
func RunSearches() {
	fmt.Println("\nGoogle1")
	DoSearch(Google1)

	fmt.Println("\nGoogle2")
	DoSearch(Google2)

	fmt.Println("\nGoogle3")
	DoSearch(Google3)

	fmt.Println("\nGoogle4")
	DoSearch(Google4)
}
